"""empty message

Revision ID: 3e9f115faa3a
Revises: 
Create Date: 2023-09-19 14:50:44.792328

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '3e9f115faa3a'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('system_config',
    sa.Column('type', sa.String(length=30), server_default='', nullable=True, comment='类型'),
    sa.Column('name', sa.String(length=60), server_default='', nullable=False, comment='键'),
    sa.Column('value', sa.Text(), nullable=False, comment='值'),
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False, comment='主键ID'),
    sa.Column('is_disable', sa.Boolean(), server_default=sa.text('0'), nullable=True, comment='是否禁用: 0=否, 1=是'),
    sa.Column('create_time', sa.DateTime(), nullable=False, comment='创建时间'),
    sa.Column('update_time', sa.DateTime(), nullable=False, comment='更新时间'),
    sa.PrimaryKeyConstraint('id'),
    mysql_engine='InnoDB'
    )
    op.create_table('system_dept',
    sa.Column('pid', sa.Integer(), server_default=sa.text('0'), nullable=False, comment='上级主键'),
    sa.Column('name', sa.String(length=100), server_default='', nullable=False, comment='部门名称'),
    sa.Column('duty', sa.String(length=30), server_default='', nullable=False, comment='负责人名'),
    sa.Column('mobile', sa.String(length=30), server_default='', nullable=False, comment='联系电话'),
    sa.Column('sort', sa.Integer(), server_default=sa.text('0'), nullable=False, comment='排序编号'),
    sa.Column('is_stop', sa.Boolean(), server_default=sa.text('0'), nullable=False, comment='是否停用: 0=否, 1=是'),
    sa.Column('is_delete', sa.Boolean(), server_default=sa.text('0'), nullable=False, comment='是否删除: [0=否, 1=是]'),
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False, comment='主键ID'),
    sa.Column('is_disable', sa.Boolean(), server_default=sa.text('0'), nullable=True, comment='是否禁用: 0=否, 1=是'),
    sa.Column('create_time', sa.DateTime(), nullable=False, comment='创建时间'),
    sa.Column('update_time', sa.DateTime(), nullable=False, comment='更新时间'),
    sa.PrimaryKeyConstraint('id'),
    comment='系统部门管理表',
    mysql_auto_increment='1',
    mysql_charset='utf8mb4',
    mysql_collate='utf8mb4_general_ci',
    mysql_engine='InnoDB',
    mysql_row_format='Dynamic'
    )
    op.create_table('system_menu',
    sa.Column('pid', sa.Integer(), server_default=sa.text('0'), nullable=True, comment='上级菜单'),
    sa.Column('menu_type', sa.String(length=2), server_default='D', nullable=True, comment='菜单类型: [D=目录，M=菜单，B=按钮]'),
    sa.Column('menu_name', sa.String(length=100), server_default='', nullable=False, comment='菜单名称'),
    sa.Column('menu_icon', sa.String(length=100), server_default='', nullable=False, comment='菜单图标'),
    sa.Column('menu_sort', sa.Integer(), server_default=sa.text('0'), nullable=False, comment='菜单排序'),
    sa.Column('perms', sa.String(length=100), server_default='', nullable=False, comment='权限标识'),
    sa.Column('paths', sa.String(length=100), server_default='', nullable=False, comment='路由地址'),
    sa.Column('component', sa.String(length=200), server_default='', nullable=False, comment='前端组件'),
    sa.Column('selected', sa.String(length=200), server_default='', nullable=False, comment='选中路径'),
    sa.Column('params', sa.String(length=200), server_default='', nullable=False, comment='路由参数'),
    sa.Column('is_cache', sa.Boolean(), server_default=sa.text('0'), nullable=False, comment='是否缓存: 0=否, 1=是'),
    sa.Column('is_show', sa.Boolean(), server_default=sa.text('1'), nullable=False, comment='是否显示: 0=否, 1=是'),
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False, comment='主键ID'),
    sa.Column('is_disable', sa.Boolean(), server_default=sa.text('0'), nullable=True, comment='是否禁用: 0=否, 1=是'),
    sa.Column('create_time', sa.DateTime(), nullable=False, comment='创建时间'),
    sa.Column('update_time', sa.DateTime(), nullable=False, comment='更新时间'),
    sa.PrimaryKeyConstraint('id'),
    mysql_engine='InnoDB'
    )
    op.create_table('system_post',
    sa.Column('code', sa.String(length=30), server_default=sa.text('0'), nullable=False, comment='岗位编码'),
    sa.Column('name', sa.String(length=30), server_default='', nullable=False, comment='岗位名称'),
    sa.Column('remarks', sa.String(length=250), nullable=False, comment='岗位备注'),
    sa.Column('sort', sa.Integer(), server_default=sa.text('0'), nullable=False, comment='排序编号'),
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False, comment='主键ID'),
    sa.Column('is_disable', sa.Boolean(), server_default=sa.text('0'), nullable=True, comment='是否禁用: 0=否, 1=是'),
    sa.Column('create_time', sa.DateTime(), nullable=False, comment='创建时间'),
    sa.Column('update_time', sa.DateTime(), nullable=False, comment='更新时间'),
    sa.Column('is_delete', sa.Boolean(), server_default=sa.text('0'), nullable=True, comment='是否删除: [0=否, 1=是]'),
    sa.Column('delete_time', sa.DateTime(), nullable=True, comment='删除时间'),
    sa.PrimaryKeyConstraint('id'),
    comment='系统岗位管理表',
    mysql_auto_increment='1',
    mysql_charset='utf8mb4',
    mysql_collate='utf8mb4_general_ci',
    mysql_engine='InnoDB',
    mysql_row_format='Dynamic'
    )
    op.create_table('system_role',
    sa.Column('name', sa.String(length=100), server_default='', nullable=False, comment='角色名称'),
    sa.Column('remark', sa.String(length=200), server_default='', nullable=False, comment='备注信息'),
    sa.Column('sort', sa.Integer(), server_default=sa.text('0'), nullable=False, comment='角色排序'),
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False, comment='主键ID'),
    sa.Column('is_disable', sa.Boolean(), server_default=sa.text('0'), nullable=True, comment='是否禁用: 0=否, 1=是'),
    sa.Column('create_time', sa.DateTime(), nullable=False, comment='创建时间'),
    sa.Column('update_time', sa.DateTime(), nullable=False, comment='更新时间'),
    sa.PrimaryKeyConstraint('id'),
    comment='系统角色管理表',
    mysql_auto_increment='1',
    mysql_charset='utf8mb4',
    mysql_collate='utf8mb4_general_ci',
    mysql_engine='InnoDB',
    mysql_row_format='Dynamic'
    )
    op.create_table('system_user',
    sa.Column('username', sa.String(length=32), server_default='', nullable=False, comment='用户账号'),
    sa.Column('nickname', sa.String(length=32), server_default='', nullable=True, comment='用户昵称'),
    sa.Column('password', sa.String(length=200), server_default='', nullable=False, comment='用户密码'),
    sa.Column('avatar', sa.String(length=200), server_default='', nullable=True, comment='用户头像'),
    sa.Column('sort', sa.Integer(), server_default=sa.text('0'), nullable=False, comment='排序编号'),
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False, comment='主键ID'),
    sa.Column('is_disable', sa.Boolean(), server_default=sa.text('0'), nullable=True, comment='是否禁用: 0=否, 1=是'),
    sa.Column('create_time', sa.DateTime(), nullable=False, comment='创建时间'),
    sa.Column('update_time', sa.DateTime(), nullable=False, comment='更新时间'),
    sa.Column('last_login_ip', sa.String(length=30), server_default='', nullable=True, comment='最后登录IP'),
    sa.Column('last_login_time', sa.DateTime(), nullable=True, comment='最后登录时间'),
    sa.Column('is_delete', sa.Boolean(), server_default=sa.text('0'), nullable=True, comment='是否删除: [0=否, 1=是]'),
    sa.Column('delete_time', sa.DateTime(), nullable=True, comment='删除时间'),
    sa.PrimaryKeyConstraint('id'),
    mysql_engine='InnoDB'
    )
    op.create_table('system_role_menu',
    sa.Column('role_id', sa.Integer(), nullable=False, comment='角色ID'),
    sa.Column('menu_id', sa.Integer(), nullable=False, comment='菜单ID'),
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False, comment='主键ID'),
    sa.Column('is_disable', sa.Boolean(), server_default=sa.text('0'), nullable=True, comment='是否禁用: 0=否, 1=是'),
    sa.Column('create_time', sa.DateTime(), nullable=False, comment='创建时间'),
    sa.Column('update_time', sa.DateTime(), nullable=False, comment='更新时间'),
    sa.ForeignKeyConstraint(['menu_id'], ['system_menu.id'], ),
    sa.ForeignKeyConstraint(['role_id'], ['system_role.id'], ),
    sa.PrimaryKeyConstraint('id'),
    mysql_engine='InnoDB'
    )
    op.create_table('system_user_dept',
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('dept_id', sa.Integer(), nullable=False),
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False, comment='主键ID'),
    sa.Column('is_disable', sa.Boolean(), server_default=sa.text('0'), nullable=True, comment='是否禁用: 0=否, 1=是'),
    sa.Column('create_time', sa.DateTime(), nullable=False, comment='创建时间'),
    sa.Column('update_time', sa.DateTime(), nullable=False, comment='更新时间'),
    sa.ForeignKeyConstraint(['dept_id'], ['system_dept.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['system_user.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    mysql_engine='InnoDB'
    )
    op.create_table('system_user_post',
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('post_id', sa.Integer(), nullable=False),
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False, comment='主键ID'),
    sa.Column('is_disable', sa.Boolean(), server_default=sa.text('0'), nullable=True, comment='是否禁用: 0=否, 1=是'),
    sa.Column('create_time', sa.DateTime(), nullable=False, comment='创建时间'),
    sa.Column('update_time', sa.DateTime(), nullable=False, comment='更新时间'),
    sa.ForeignKeyConstraint(['post_id'], ['system_post.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['system_user.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    mysql_engine='InnoDB'
    )
    op.create_table('system_user_role',
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('role_id', sa.Integer(), nullable=False),
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False, comment='主键ID'),
    sa.Column('is_disable', sa.Boolean(), server_default=sa.text('0'), nullable=True, comment='是否禁用: 0=否, 1=是'),
    sa.Column('create_time', sa.DateTime(), nullable=False, comment='创建时间'),
    sa.Column('update_time', sa.DateTime(), nullable=False, comment='更新时间'),
    sa.ForeignKeyConstraint(['role_id'], ['system_role.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['system_user.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    mysql_engine='InnoDB'
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('system_user_role')
    op.drop_table('system_user_post')
    op.drop_table('system_user_dept')
    op.drop_table('system_role_menu')
    op.drop_table('system_user')
    op.drop_table('system_role')
    op.drop_table('system_post')
    op.drop_table('system_menu')
    op.drop_table('system_dept')
    op.drop_table('system_config')
    # ### end Alembic commands ###
